### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by kevint052** [kc1212/consensus-thesis-code#10]
Hi,

I tried running pytest on Mac and Linux but on both I get this error :

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_trustchain.py ___________________
tests/test_trustchain.py:4: in <module>
    from src.trustchain import *
src/trustchain/__init__.py:1: in <module>
    from trustchain import *
src/trustchain/trustchain.py:1: in <module>
    import libnacl
/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py:83: in <module>
    nacl = _get_nacl()
/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py:81: in _get_nacl
    raise OSError(msg)
E   OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.41 seconds ============================

Have you an idea how to solve this issue ?

Best Regards,

**Comment by kc1212** [comment]
Hi, you need to libsodium https://download.libsodium.org/doc/installation/, the crypto library in C. Most distributions should have it packaged.  

On 15 February 2018 00:01:23 CET, KevinTAN52 <notifications@github.com> wrote:
>Hi,
>
>I tried running pytest on Mac and Linux but on both I get this error :
>
>==================================== ERRORS
>====================================
>__________________ ERROR collecting tests/test_trustchain.py
>___________________
>tests/test_trustchain.py:4: in <module>
>    from src.trustchain import *
>src/trustchain/__init__.py:1: in <module>
>    from trustchain import *
>src/trustchain/trustchain.py:1: in <module>
>    import libnacl
>/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py:83: in
><module>
>    nacl = _get_nacl()
>/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py:81: in
>_get_nacl
>    raise OSError(msg)
>E   OSError: Could not locate nacl lib, searched for libsodium.so,
>libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10,
>libsodium.so.5, libsodium.so.4,
>!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection
>!!!!!!!!!!!!!!!!!!!!
>=========================== 1 error in 0.41 seconds
>============================
>
>Have you an idea how to solve this issue ?
>
>Best Regards,
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kc1212/checo/issues/10

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kevint052** [comment]
It worked thanks !
